### ISSUE TITLE
不要なコメント行は削除する

### ISSUE THREAD

**Issue by norotime** [marie1509/original_app#1]
https://github.com/marie1509/be-a-gift-giver/blob/7902a7589a35436afba8565a0595fc7b819290cc/app/controllers/didbuys_controller.rb#L6

@marie1509 masterにコミットされたものは本番環境のソースです。過去の負の遺産のようなコードコメントは削除してください。お客様に見られますよー。

**Comment by marie1509** [comment]
close#1

**Comment by norotime** [comment]
@marie1509 どのコミットで対応していますか？
ここで見れるといいですね。
コミットメッセージは、
close#1
ではなく
close #1
と#の前に半角スペースが必要かもです。
